# -*- coding: utf-8 -*-
"""Arya Vast Python Assignment 1 List and Loops

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14HHi8YFGxVXyZ0MmelOmw87AwymuiAsy

Find the sum of elements in a list
"""

# Add up the lengths of different DNA fragments using sum function.
dna_lengths = [350, 1120, 570, 20]
total_length = sum(dna_lengths)
print(f"DNA lengths: {dna_lengths} → Total length: {total_length}")

""" Find the sum of squares of elements in a list"""

# Square each cell count from samples and add them together
cell_counts = [2, 3, 4]
sum_of_squares = sum([c**2 for c in cell_counts])
print("Sum of squares:", sum_of_squares)

"""Find the product of all elements in a list"""

# Multiply bacterial growth factors to get total growth
growth_factors = [4, 2, 2]
total_growth = 1
for g in growth_factors:
    total_growth *= g
print("Growth factors:", growth_factors)
print("Total growth:", total_growth)

""" Find the largest element in a list"""

# Find the heaviest sample weight
sample_weights = [15, 8, 29, 21, 11]
largest = sample_weights[0]
for weight in sample_weights:
  if weight > largest:
    largest = weight
print(f"Example: l = {sample_weights} → Output: {largest}")

""" Find the smallest element in a list"""

# Find the lightest sample weight
sample_weights = [15, 8, 29, 21, 11]
smallest = sample_weights[0]
for weight in sample_weights:
  if weight < smallest:
    smallest = weight
print(f"Example: l = {sample_weights} → Output: {smallest}")

"""Count how many even numbers are in a list"""

# Flowers with an even number of petals
petal_counts = [3, 5, 6, 4, 8]
even_count = 0
for petals in petal_counts:
  if petals % 2 == 0:
    even_count = even_count + 1
print(f"Example: l = {petal_counts} → Output: {even_count}")

"""Count how many odd numbers are in a list"""

# Mondays that fall on an odd-numbered date
monday_dates = [6, 13, 20, 27]
odd_count = 0
for date in monday_dates:
  if date % 2 != 0:
    odd_count = odd_count + 1
print(f"Example: l = {monday_dates} → Output: {odd_count}")

"""Find the sum of even numbers in a list"""

# Sum the petals from flowers with an even number of petals
petal_counts = [3, 5, 6, 4, 8]
sum_of_evens = 0
for petals in petal_counts:
  if petals % 2 == 0:
    sum_of_evens = sum_of_evens + petals
print(f"Example: l = {petal_counts} → Output: {sum_of_evens}")

"""Find the sum of odd numbers in a list"""

# Sum the odd-numbered dates for all Mondays
monday_dates = [6, 13, 20, 27]
sum_of_odds = 0
for date in monday_dates:
  if date % 2 != 0:
    sum_of_odds = sum_of_odds + date
print(f"Example: l = {monday_dates} → Output: {sum_of_odds}")

"""Reverse a list using a while loop"""

# Reverse a simple gene sequence represented by numbers
gene_sequence = [1, 4, 2, 3]
reversed_sequence = []
index = len(gene_sequence) - 1
while index >= 0:
  reversed_sequence.append(gene_sequence[index])
  index = index - 1
print(f"Example: l = {gene_sequence} → Output: {reversed_sequence}")