# -*- coding: utf-8 -*-
"""EDA assignment Arya Vast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V0TKt4hE-G9K9bFwE9hxWqP2T6j-mW8A

Step 1: Dataset Selection
"""

# Load the dataset (pd.read_csv() or similar).
import seaborn as sns
import pandas as pd

datasets = sns.get_dataset_names()
print(datasets)

# Display the first few rows and dataset info.
df = sns.load_dataset("tips")
print(df.head())
print(df.info())

"""Step 2: Data Loading and Cleaning"""

# Check for missing values and handle them (drop, fill, etc.).
missing_values = df.isnull().sum()
print(missing_values)

df = df.dropna()
print(df.isnull().sum())

# Columns remaned and converted to appropriate data types

df = df.rename(columns={"total_bill": "TotalBill", "tip": "Tip", "sex": "Gender", "smoker": "SmokerStatus", "day": "Day", "time": "MealTime", "size": "GroupSize"})

df["TotalBill"] = df["TotalBill"].astype(float)
df["Tip"] = df["Tip"].astype(float)
df["GroupSize"] = df["GroupSize"].astype(int)

print(df.dtypes)
print(df.head())

"""Step 3: Descriptive Statistics and Exploration
Use NumPy and Pandas to:
"""

# Generate summary statistics (.describe(), .info(), .value_counts()).
for col in df.select_dtypes(include=["object", "category"]).columns:
    print(df[col].value_counts())

# Identify numerical vs categorical columns.
numerical_cols = df.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_cols = df.select_dtypes(include=["object", "category"]).columns.tolist()

print("Numerical Columns:", numerical_cols)
print("Categorical Columns:", categorical_cols)

# Compute mean, median, mode, standard deviation, etc.
mean_values = df[numerical_cols].mean()
median_values = df[numerical_cols].median()
mode_values = df[numerical_cols].mode().iloc[0]
std_values = df[numerical_cols].std()

print("Mean Values:\n", mean_values)
print("Median Values:\n", median_values)
print("Mode Values:\n", mode_values)
print("Standard Deviation:\n", std_values)

# Check for outliers and data distribution.
for col in numerical_cols:
    sns.boxplot(x=df[col])
    plt.title(f"Outliers in {col}")
    plt.show()

for col in numerical_cols:
    sns.histplot(df[col], kde=True)
    plt.title(f"Distribution of {col}")
    plt.show()

"""Step 4: Data Visualization
Use Matplotlib and Seaborn to visualize:
"""

# Univariate Analysis – Histograms, Boxplots, Countplots.


df = sns.load_dataset("tips")

sns.histplot(df["total_bill"], kde=True)
plt.show()

sns.boxplot(x=df["tip"])
plt.show()

sns.countplot(x=df["day"])
plt.show()

# Bivariate Analysis – Scatterplots, lineplot.

sns.scatterplot(x="total_bill", y="tip", data=df)
plt.show()

sns.lineplot(x="size", y="tip", data=df)
plt.show()

# Correlation Analysis – Correlation matrix using sns.heatmap().
corr = df.corr(numeric_only=True)
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.show()

# Categorical Analysis – Bar plots or violin plots.
sns.barplot(x="day", y="total_bill", data=df)
plt.show()

sns.violinplot(x="smoker", y="tip", data=df)
plt.show()

# Distribution Plots – sns.distplot() or sns.histplot().
sns.histplot(df["tip"], kde=True)
plt.show()

"""Step 5: Insights and Conclusion

1. Summary of Key Findings:

The dataset contains 244 records of restaurant tips with 7 columns: total bill, tip amount, gender, smoker status, day, time, and group size. The average total bill was approximately 19.79 dollars, while the average tip was 3.00 dollars. Both total bill and tip amounts show a right-skewed distribution, meaning most bills and tips are on the lower side, with fewer high values. Outliers were observed in the 'TotalBill', 'Tip', and 'GroupSize' variables.

2. Mention any patterns, relationships, or anomalies you discovered.

There is a strong positive correlation (0.68) between total bill and tip, meaning larger bills usually get larger tips. Group size moderately increases total bill (0.60) and tip (0.49). Weekends and dinner times have higher bills and more customers. Smoker status does not strongly affect tips. Males appear more frequently than females in the dataset. Some outliers indicate occasional unusually high bills or tips.

3. Suggest possible next steps (e.g., predictive modeling, data collection improvements, etc.)

Next possible next steps could be building a predictive model using methods like Linear regression  to estimate tips based on features like TotalBill, GroupSize, Day, SmokerStatus etc.
Data Collection can be improved by collecting more data across different restaurants, days, and times to improve accuracy.
Data can be enhaced by adding features like tip percentage and weekend indicators.

Short summary:

The Tips data set (244 rows, 7 columns) presents restaurant bills and tips with information such as gender, day, time, and group size. Tips average is 15 to 16% of the bill and is more during dinners and weekends. Males give  more tips, and larger bills eventually receive more tips. Most of the bills are less, with a few large-party extremes. Tipping behavior of the customers generally strongly represents time, day, and bill size.
"""