# -*- coding: utf-8 -*-
"""ARYA VAST PYTHON 2 ASSIGNMENT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1COXrmL0pDpV4cjkpCCGTXAx9Es6X48I5

**Question 1: Student Management System**
"""

class Person:
    """A base class to represent a person with a name and age."""
    def __init__(self, name, age):
        self.name = name
        self.age = age

class Student(Person):
    """A subclass that inherits from Person and adds a grade."""
    def __init__(self, name, age, grade):
        super().__init__(name, age)
        self.grade = grade

def add_students_and_save():
    """Asks the user for student details and saves them to a file."""
    print("--- Add New Students ---")

    with open("students.txt", "a") as file:
        while True:
            name = input("Enter student's name: ")
            age = input("Enter student's age: ")
            grade = input("Enter student's grade: ")
            student = Student(name, age, grade)

            file.write(f"{student.name},{student.age},{student.grade}\n")
            print(f" Student '{name}' has been added.")

            another = input("Add another student? (yes/no): ").lower()
            if another != 'yes':
                break
def display_students():
    """Reads all student details from the file and prints them."""
    print("\n--- All Saved Student Details ---")
    try:
        with open("students.txt", "r") as file:
            for line in file:

                name, age, grade = line.strip().split(',')
                print(f"Name: {name}, Age: {age}, Grade: {grade}")
    except FileNotFoundError:
        print("No students have been saved yet. Please add a student first.")

if __name__ == "__main__":
    add_students_and_save()
    display_students()

"""**Question 2: Bank Account Simulation**"""

class BankAccount:
    """A class to simulate a simple bank account."""
    def __init__(self, initial_balance=0):

        self.__balance = initial_balance

    def log_transaction(self, transaction_details):
        """Appends a transaction record to the log file."""
        with open("transactions.txt", "a") as file:
            file.write(transaction_details + "\n")

    def deposit(self, amount):
        """Adds money to the balance and logs the transaction."""
        if amount > 0:
            self.__balance += amount
            self.log_transaction(f"Deposited: Rs.{amount:.2f}")
            print(f"Successfully deposited Rs.{amount:.2f}.")
        else:
            print("Deposit amount must be positive.")

    def withdraw(self, amount):
        """Withdraws money if funds are sufficient and logs the transaction."""
        if amount > 0 and amount <= self.__balance:
            self.__balance -= amount
            self.log_transaction(f"Withdrew: Rs.{amount:.2f}")
            print(f"Successfully withdrew Rs.{amount:.2f}.")
        else:

            self.log_transaction(f"Failed withdrawal attempt: Rs.{amount:.2f}")
            print("Withdrawal failed. Either amount is invalid or funds are insufficient.")

    def get_balance(self):
        """Returns the current balance."""
        print(f"Your current balance is: Rs.{self.__balance:.2f}")
        return self.__balance


def main():
    """The main function to run the bank simulation."""
    account = BankAccount(100)
    print("Welcome to your bank account!")

    while True:
        print("\nMenu")
        print("1. Deposit Money")
        print("2. Withdraw Money")
        print("3. Check Balance")
        print("4. Exit and Show Transactions")

        choice = input("Please choose an option (1-4): ")

        if choice == '1':
            amount = float(input("Enter amount to deposit: "))
            account.deposit(amount)
        elif choice == '2':
            amount = float(input("Enter amount to withdraw: "))
            account.withdraw(amount)
        elif choice == '3':
            account.get_balance()
        elif choice == '4':
            print("\nFull Transaction History")
            try:
                with open("transactions.txt", "r") as file:
                    print(file.read())
            except FileNotFoundError:
                print("No transactions were made.")
            print("Thank you for banking with us!")
            break
        else:
            print("Invalid choice. Please enter a number between 1 and 4.")
if __name__ == "__main__":
    main()

"""
**Question 3: Temperature Converter Module**"""

def celsius_to_fahrenheit(c):
    """Converts Celsius to Fahrenheit."""
    return (c * 9/5) + 32

def fahrenheit_to_celsius(f):
    """Converts Fahrenheit to Celsius."""
    return (f - 32) * 5/9

def celsius_to_kelvin(c):
    """Converts Celsius to Kelvin."""
    return c + 273.15

import temperature

def main():
    """Asks the user for a temperature and conversion type, then displays the result."""
    print("--- Temperature Converter ---")
    print("1. Celsius to Fahrenheit")
    print("2. Fahrenheit to Celsius")
    print("3. Celsius to Kelvin")

    choice = input("Choose a conversion (1-3): ")
    temp_str = input("Enter the temperature to convert: ")

    try:
        temp = float(temp_str)
        if choice == '1':
            result = temperature.celsius_to_fahrenheit(temp)
            print(f"{temp}°C is equal to {result:.2f}°F")
        elif choice == '2':
            result = temperature.fahrenheit_to_celsius(temp)
            print(f"{temp}°F is equal to {result:.2f}°C")
        elif choice == '3':
            result = temperature.celsius_to_kelvin(temp)
            print(f"{temp}°C is equal to {result:.2f}K")
        else:
            print("Invalid conversion choice. Please run the program again.")

    except ValueError:
        print("Invalid temperature. Please enter a number.")
if __name__ == "__main__":
    main()